config/routes.rb
# Locomotive::Application.routes.draw do |map|
Rails.application.routes.draw do

  # admin authentication
  devise_for :admin, :class_name => 'Account', :controllers => { :sessions => 'admin/sessions', :passwords => 'admin/passwords' }

  as :admin do
    get '/admin' => 'admin/sessions#new'
  end

  # admin interface for each website
  namespace 'admin' do
    root :to => 'sessions#new'

    resources :pages do
      put :sort, :on => :member
      get :get_path, :on => :collection
    end

    resources :snippets

    resources :sites

    resource :current_site, :controller => 'current_site'

    resources :accounts

    resource :my_account, :controller => 'my_account'

    resources :memberships

    resources :theme_assets do
      get :all, :action => 'index', :on => :collection, :defaults => { :all => true }
    end

    resources :assets

    resources :content_types

    resources :contents, :path => 'content_types/:slug/contents' do
      put :sort, :on => :collection
    end

    resources :api_contents, :path => 'api/:slug/contents', :controller => 'api_contents', :only => [:create]

    resources :custom_fields, :path => 'custom/:parent/:slug/fields'

    resources :cross_domain_sessions, :only => [:new, :create]

    resource :import, :only => [:new, :show, :create], :controller => 'import'

    resource :export, :only => [:new], :controller => 'export'

    # installation guide
    match '/installation' => 'installation#show', :defaults => { :step => 1 }, :as => :installation
    match '/installation/:step' => 'installation#show', :as => :installation_step

  end

  # sitemap
  match '/sitemap.xml' => 'admin/sitemaps#show', :format => 'xml'

  # robots.txt
  match '/robots.txt' => 'admin/robots#show', :format => 'txt'

  # magic urls
  match '/' => 'admin/rendering#show'
  match '*path/edit' => 'admin/rendering#edit'
  match '*path' => 'admin/rendering#show'
end

app/models/theme_asset.rb
class ThemeAsset

  include Locomotive::Mongoid::Document

  ## extensions ##
  include Extensions::Asset::Types

  ## fields ##
  field :local_path
  field :content_type
  field :width, :type => Integer
  field :height, :type => Integer
  field :size, :type => Integer
  field :folder, :default => nil
  mount_uploader :source, ThemeAssetUploader

  ## associations ##
  referenced_in :site

  ## indexes ##
  index :site_id
  index [[:site_id, Mongo::ASCENDING], [:local_path, Mongo::ASCENDING]]

  ## callbacks ##
  before_validation :store_plain_text
  before_validation :sanitize_folder
  before_validation :build_local_path

  ## validations ##
  validates_presence_of :site, :source
  validates_presence_of :plain_text_name, :if => Proc.new { |a| a.performing_plain_text? }
  validates_uniqueness_of :local_path, :scope => :site_id
  validates_integrity_of :source
  validate :content_type_can_not_changed

  ## named scopes ##

  ## accessors ##
  attr_accessor :plain_text_name, :plain_text, :plain_text_type, :performing_plain_text

  ## methods ##

  def stylesheet_or_javascript?
    self.stylesheet? || self.javascript?
  end

  def local_path(short = false)
    if short
      self.read_attribute(:local_path).gsub(/^#{self.content_type.to_s.pluralize}\//, '')
    else
      self.read_attribute(:local_path)
    end
  end

  def plain_text_name
    if not @plain_text_name_changed
      @plain_text_name ||= self.safe_source_filename
    end
    @plain_text_name.gsub(/(\.[a-z0-9A-Z]+)$/, '') rescue nil
  end

  def plain_text_name=(name)
    @plain_text_name_changed = true
    @plain_text_name = name
  end

  def plain_text
    if RUBY_VERSION =~ /1\.9/
      @plain_text ||= (self.source.read.force_encoding('UTF-8') rescue nil)
    else
      @plain_text ||= self.source.read
    end
  end

  def plain_text_type
    @plain_text_type || (stylesheet_or_javascript? ? self.content_type : nil)
  end

  def performing_plain_text?
    Boolean.set(self.performing_plain_text) || false
  end

  def store_plain_text
    self.content_type ||= @plain_text_type if self.performing_plain_text?

    data = self.performing_plain_text? ? self.plain_text : self.source.read

    return if !self.stylesheet_or_javascript? || self.plain_text_name.blank? || data.blank?

    sanitized_source = self.escape_shortcut_urls(data)

    self.source = CarrierWave::SanitizedFile.new({
      :tempfile => StringIO.new(sanitized_source),
      :filename => "#{self.plain_text_name}.#{self.stylesheet? ? 'css' : 'js'}"
    })
  end

  def to_liquid
    { :url => self.source.url }.merge(self.attributes).stringify_keys
  end

  def self.all_grouped_by_folder(site)
    assets = site.theme_assets.order_by([[:slug, :asc]])
    assets.group_by { |a| a.folder.split('/').first.to_sym }
  end

  protected

  def safe_source_filename
    self.source_filename || self.source.send(:original_filename) rescue nil
  end

  def sanitize_folder
    self.folder = self.content_type.to_s.pluralize if self.folder.blank?

    # no accents, no spaces, no leading and ending trails
    self.folder = ActiveSupport::Inflector.transliterate(self.folder).gsub(/(\s)+/, '_').gsub(/^\//, '').gsub(/\/$/, '')

    # folder should begin by a root folder
    if (self.folder =~ /^(stylesheets|javascripts|images|medias|fonts)/).nil?
      self.folder = File.join(self.content_type.to_s.pluralize, self.folder)
    end
  end

  def build_local_path
    if filename = self.safe_source_filename
      self.local_path = File.join(self.folder, filename)
    else
      nil
    end
  end

  def escape_shortcut_urls(text)
    return if text.blank?

    text.gsub(/[("'](\/(stylesheets|javascripts|images|medias)\/(([^;.]+)\/)*([a-z_\-0-9]+)\.[a-z]{2,3})[)"']/) do |path|

      sanitized_path = path.gsub(/[("')]/, '').gsub(/^\//, '')

      if asset = self.site.theme_assets.where(:local_path => sanitized_path).first
        "#{path.first}#{asset.source.url}#{path.last}"
      else
        path
      end
    end
  end

  def content_type_can_not_changed
    self.errors.add(:source, :extname_changed) if !self.new_record? && self.content_type_changed?
  end

end

app/controllers/admin/theme_assets_controller.rb
module Admin
  class ThemeAssetsController < BaseController

    include ActionView::Helpers::SanitizeHelper
    extend ActionView::Helpers::SanitizeHelper::ClassMethods
    include ActionView::Helpers::TextHelper
    include ActionView::Helpers::NumberHelper

    sections 'settings', 'theme_assets'

    respond_to :json, :only => [:create, :update]

    before_filter :sanitize_params, :only => [:create, :update]

    def index
      @assets = ThemeAsset.all_grouped_by_folder(current_site)
      @js_and_css_assets = (@assets[:javascripts] || []) + (@assets[:stylesheets] || [])

      if request.xhr?
        @images = @assets[:images] || []
        render :action => 'images', :layout => false and return
      else
        @snippets = current_site.snippets.order_by([[:name, :asc]]).all.to_a
      end
    end

    def edit
      resource.performing_plain_text = true if resource.stylesheet_or_javascript?
      edit!
    end

    def create
      create! do |success, failure|
        success.json do
          render :json => {
            :status       => 'success',
            :url          => @theme_asset.source.url,
            :local_path   => @theme_asset.local_path(true),
            :size         => number_to_human_size(@theme_asset.size),
            :date         => l(@theme_asset.updated_at, :format => :short)
          }
        end
        failure.json { render :json => { :status => 'error' } }
      end
    end

    protected

    def sanitize_params
      params[:theme_asset] = { :source => params[:file] } if params[:file]
    end

  end

end

app/views/admin/theme_assets/_asset.html.haml
- edit = local_assigns.key?(:edit) ? edit : true

%li{ :class => (asset.new_record? ? 'new-asset' : 'asset') }
  %em
  %strong= link_to asset.local_path(!edit), edit ? edit_admin_theme_asset_path(asset) : asset.source.url, :'data-local-path' => asset.local_path
  .more
    %span.size= number_to_human_size(asset.size)
    &mdash;
    %span!= t('.updated_at')
    %span.date= l asset.updated_at, :format => :short

    - if edit && can?(:destroy, asset)
      = link_to image_tag('admin/list/icons/trash.png'), admin_theme_asset_path(asset), :class => 'remove', :confirm => t('admin.messages.confirm'), :method => :delete

app/views/admin/theme_assets/_form.html.haml
- content_for :head do
  = include_javascripts :image_picker, :theme_assets
  = include_stylesheets :fancybox

= f.hidden_field :performing_plain_text

#file-selector{ :class => "selector #{'hidden' if display_plain_text?(@theme_asset)}" }
  = f.inputs :name => :information do
    = f.input :source

  - if allow_plain_text_editing?(@theme_asset)
    %span.alt
      != t('admin.theme_assets.form.choose_plain_text')

- if allow_plain_text_editing?(@theme_asset)
  #text-selector{ :class => "selector #{'hidden' unless display_plain_text?(@theme_asset)}", :style => "#{'display: none' unless display_plain_text?(@theme_asset)}" }
    = f.inputs :name => :code, :class => 'inputs code' do

      - if @theme_asset.new_record?
        = f.input :plain_text_name

        = f.custom_input :plain_text_type do
          = f.select :plain_text_type, %w(stylesheet javascript)

      = f.custom_input :plain_text, :css => 'full', :with_label => false do
        %code{ :class => (@theme_asset.size && @theme_asset.size > 40000 ? 'nude' : (@theme_asset.content_type || 'stylesheet')) }
          = f.text_area :plain_text
        .more
          = link_to t('admin.image_picker.link'), admin_theme_assets_path, :id => 'image-picker-link', :class => 'picture'

    %span.alt
      != t('admin.theme_assets.form.choose_file')

= f.foldable_inputs :name => :options do
  = f.input :folder

app/views/admin/theme_assets/edit.html.haml
- title t('.title', :file => @theme_asset.source_filename)

- content_for :submenu do
  = render_cell 'admin/settings_menu', :show

- if can?(:manage, ThemeAsset)
  - content_for :buttons do
    = admin_button_tag t('admin.theme_assets.index.new'), new_admin_theme_asset_url, :class => 'new'

%p
  - if %w(image javascript stylesheet).include?(@theme_asset.content_type.to_s)
    != t(".help_#{@theme_asset.content_type}", :path => @theme_asset.local_path(true), :width => @theme_asset.width, :height => @theme_asset.height)

  != t('.help', :url => @theme_asset.source.url)


= semantic_form_for @theme_asset, :url => admin_theme_asset_url(@theme_asset), :html => { :multipart => true, :class => 'save-with-shortcut' } do |form|

  = render 'form', :f => form

  = render 'admin/shared/form_actions', :back_url => admin_theme_assets_url, :button_label => :update

app/views/admin/theme_assets/images.html.haml
#theme-images.asset-picker
  %h2!= t('.title')

  .actions
    = admin_button_tag t('admin.theme_assets.index.new'), admin_theme_assets_url(:json), :class => 'button small add', :id => 'upload-link'

  - if @images.empty?
    %p.no-items!= t('.no_items')

  %ul.list.theme-assets
    = render 'asset', :asset => current_site.theme_assets.build(:updated_at => Time.now, :local_path => 'images/new.jpg', :content_type => 'image'), :edit => false

    = render :partial => 'asset', :collection => @images, :locals => { :edit => false }

    %li.clear

app/views/admin/theme_assets/index.html.haml
- title t('.title')

- content_for :submenu do
  = render_cell 'admin/settings_menu', :show

- content_for :buttons do
  = admin_button_tag t('admin.snippets.index.new'), new_admin_snippet_url, :class => 'new' if can?(:manage, Snippet)
  = admin_button_tag :new, new_admin_theme_asset_url, :class => 'new' if can?(:manage, ThemeAsset)

%p!= t('.help')

- if can?(:manage, Snippet)
  %h3!= t('.snippets')
  - if @snippets.empty?
    %p.no-items!= t('admin.snippets.index.no_items', :url => new_admin_snippet_url)
  - else
    %ul.list.theme-assets
      = render @snippets

  %br

- if can?(:manage, ThemeAsset)
  %h3!= t('.css_and_js')
  - if @js_and_css_assets.empty?
    %p.no-items!= t('.no_items', :url => new_admin_theme_asset_url)
  - else
    %ul.list.theme-assets
      = render :partial => 'asset', :collection => @js_and_css_assets

  %br

%h3!= t('.images')
- if @assets[:images].nil?
  %p.no-items!= t('.no_items', :url => new_admin_theme_asset_url)
- else
  %ul.list.theme-assets
    = render :partial => 'asset', :collection => @assets[:images]

- if can?(:manage, ThemeAsset)
  - if @assets[:fonts]
    %br

    %h3!= t('.fonts')
    %ul.list.theme-assets
      = render :partial => 'asset', :collection => @assets[:fonts]

- if @assets[:medias]
  %br

  %h3!= t('.medias')
  %ul.list.theme-assets
    = render :partial => 'asset', :collection => @assets[:medias]

app/views/admin/theme_assets/new.html.haml
- title t('.title')

- content_for :submenu do
  = render_cell 'admin/settings_menu', :show

%p!= t('.help')

= semantic_form_for @theme_asset, :url => admin_theme_assets_url, :html => { :multipart => true } do |form|

  = render 'form', :f => form

  = render 'admin/shared/form_actions', :back_url => admin_theme_assets_url, :button_label => :create