config/routes.rb
# Locomotive::Application.routes.draw do |map|
Rails.application.routes.draw do

  # admin authentication
  devise_for :admin, :class_name => 'Account', :controllers => { :sessions => 'admin/sessions', :passwords => 'admin/passwords' }

  as :admin do
    get '/admin' => 'admin/sessions#new'
  end

  # admin interface for each website
  namespace 'admin' do
    root :to => 'sessions#new'

    resources :pages do
      put :sort, :on => :member
      get :get_path, :on => :collection
    end

    resources :snippets

    resources :sites

    resource :current_site, :controller => 'current_site'

    resources :accounts

    resource :my_account, :controller => 'my_account'

    resources :memberships

    resources :theme_assets do
      get :all, :action => 'index', :on => :collection, :defaults => { :all => true }
    end

    resources :assets

    resources :content_types

    resources :contents, :path => 'content_types/:slug/contents' do
      put :sort, :on => :collection
    end

    resources :api_contents, :path => 'api/:slug/contents', :controller => 'api_contents', :only => [:create]

    resources :custom_fields, :path => 'custom/:parent/:slug/fields'

    resources :cross_domain_sessions, :only => [:new, :create]

    resource :import, :only => [:new, :show, :create], :controller => 'import'

    resource :export, :only => [:new], :controller => 'export'

    # installation guide
    match '/installation' => 'installation#show', :defaults => { :step => 1 }, :as => :installation
    match '/installation/:step' => 'installation#show', :as => :installation_step

  end

  # sitemap
  match '/sitemap.xml' => 'admin/sitemaps#show', :format => 'xml'

  # robots.txt
  match '/robots.txt' => 'admin/robots#show', :format => 'txt'

  # magic urls
  match '/' => 'admin/rendering#show'
  match '*path/edit' => 'admin/rendering#edit'
  match '*path' => 'admin/rendering#show'
end

app/models/snippet.rb
class Snippet

  include Locomotive::Mongoid::Document

  ## fields ##
  field :name
  field :slug
  field :template

  ## associations ##
  referenced_in :site

  ## callbacks ##
  before_validation :normalize_slug
  after_save :update_templates
  after_destroy :update_templates

  ## validations ##
  validates_presence_of   :site, :name, :slug, :template
  validates_uniqueness_of :slug, :scope => :site_id

  ## methods ##

  protected

  def normalize_slug
    # TODO: refactor it
    self.slug = self.name.clone if self.slug.blank? && self.name.present?
    self.slug.permalink! if self.slug.present?
  end

  def update_templates
    return unless (self.site rescue false) # not run if the site is being destroyed

    pages = self.site.pages.any_in(:snippet_dependencies => [self.slug]).to_a

    pages.each do |page|
      self._change_snippet_inside_template(page.template.root)

      page.send(:_serialize_template)

      Page.without_callback(:save, :after, :update_template_descendants) do
        page.save(:validate => false)
      end
    end
  end

  def _change_snippet_inside_template(node)
    case node
    when Locomotive::Liquid::Tags::Snippet
      node.refresh(self) if node.slug == self.slug
    when Locomotive::Liquid::Tags::InheritedBlock
      _change_snippet_inside_template(node.parent) if node.parent
    end
    # Walk the children of this entry if they're available.
    if node.respond_to?(:nodelist)
      (node.nodelist || []).each do |child|
        self._change_snippet_inside_template(child)
      end
    end
  end

end

app/controllers/admin/snippets_controller.rb
module Admin
  class SnippetsController < BaseController

    sections 'settings', 'theme_assets'

    respond_to :json, :only => :update

    def destroy
      destroy! do |format|
        format.html { redirect_to admin_theme_assets_url }
      end
    end

  end
end

app/views/admin/snippets/_form.html.haml
- content_for :head do
  = include_javascripts :image_picker, :snippets
  = include_stylesheets :fancybox

= f.inputs :name => :information do
  = f.input :name, :wrapper_html => { :class => 'highlighted' }
  = f.input :slug, :required => false

= f.inputs :name => :code do
  = f.custom_input :template, :css => 'full', :with_label => false do
    %code{ :class => 'html' }
      = f.text_area :template
    .more
      = link_to t('admin.image_picker.link'), admin_theme_assets_path, :id => 'image-picker-link', :class => 'picture'

app/views/admin/snippets/_snippet.html.haml
%li
  %em
  %strong= link_to snippet.name, edit_admin_snippet_path(snippet)
  .more
    %span!= t('.updated_at')
    = l snippet.updated_at, :format => :short

    = link_to image_tag('admin/list/icons/trash.png'), admin_snippet_path(snippet), :class => 'remove', :confirm => t('admin.messages.confirm'), :method => :delete

app/views/admin/snippets/edit.html.haml
- title t('.title')

- content_for :submenu do
  = render_cell 'admin/settings_menu', :show

- content_for :buttons do
  = admin_button_tag t('admin.snippets.index.new'), new_admin_snippet_url, :class => 'new'

%p!= t('.help', :slug => @snippet.slug)

= semantic_form_for @snippet, :url => admin_snippet_url(@snippet), :html => { :class => 'save-with-shortcut' } do |form|

  = render 'form', :f => form

  = render 'admin/shared/form_actions', :back_url => admin_theme_assets_url, :button_label => :update

app/views/admin/snippets/new.html.haml
- title t('.title')

- content_for :submenu do
  = render_cell 'admin/settings_menu', :show

%p!= t('.help')

= semantic_form_for @snippet, :url => admin_snippets_url do |form|

  = render 'form', :f => form

  = render 'admin/shared/form_actions', :back_url => admin_theme_assets_url, :button_label => :create